name: Verify PR

on:
  pull_request:
    types: [ready_for_review, review_requested, reopened]


permissions:
  contents: read

jobs:
  build:
    if: '! github.event.pull_request.draft'
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
